Overhaul handling of setup and profile scripts to fix issues such as profile not being set before running later setup scripts.

diff --git a/workshop-images/base-environment/opt/eduk8s/sbin/start-container b/workshop-images/base-environment/opt/eduk8s/sbin/start-container
--- a/workshop-images/base-environment/opt/eduk8s/sbin/start-container
+++ b/workshop-images/base-environment/opt/eduk8s/sbin/start-container
@@ -8,13 +8,9 @@ set -eo pipefail
 
 mkdir -p $HOME/.local/share/workshop
 
-# Set defaults for all the workshop variables. There will all be overridden when
+# Set defaults for all the workshop variables. These will be overridden when
 # deploying workshops using the operator, but will be used as a fallback when
-# deploying workshops using docker-compose.
-#
-# XXX Need an INGRESS_PORT variable to specify alternate port when using only
-# HTTP (eg., 10080), and hosted with docker-compose. The value would be of form
-# ":10080" and should be empty when is standard ports.
+# deploying workshops using docker.
 
 WORKSHOP_NAME=${WORKSHOP_NAME:-workshop}
 TRAINING_PORTAL=${TRAINING_PORTAL:-workshop}
@@ -95,74 +91,6 @@ export ENABLE_WORKSHOP
 
 export DEFAULT_PAGE
 
-# Setup execution environment for Kubernetes etc.
-
-. /opt/eduk8s/etc/environment
-
-# Customize the configuration for the web console for accessing the Kubernetes
-# cluster, disabling the web console if we are not running in a Kubernetes
-# cluster or a kubeconfig has not been mounted into the container.
-#
-# XXX This should be moved into the gateway now as no longer need these details
-# in the workshop renderer. Should use a single port for the console regardless
-# of which vendor it is.
-
-if [ x"$KUBERNETES_SERVER" == x":" -a x"$KUBECONFIG" == x"" ]; then
-    ENABLE_CONSOLE=false
-fi
-
-CONSOLE_VENDOR=${CONSOLE_VENDOR:-$(workshop-definition -r '(.spec.session.applications.console.vendor // "kubernetes")')}
-
-ENABLE_CONSOLE_KUBERNETES=false
-ENABLE_CONSOLE_OCTANT=false
-
-if [ x"$ENABLE_CONSOLE" == x"true" ]; then
-    case $CONSOLE_VENDOR in
-    octant)
-        ENABLE_CONSOLE_OCTANT=true
-        if [ x"$DEFAULT_NAMESPACE" != x"" ]; then
-            CONSOLE_URL="$INGRESS_PROTOCOL://console-$SESSION_NAMESPACE.$INGRESS_DOMAIN$INGRESS_PORT_SUFFIX/#/overview/namespace/$DEFAULT_NAMESPACE"
-        else
-            CONSOLE_URL="$INGRESS_PROTOCOL://console-$SESSION_NAMESPACE.$INGRESS_DOMAIN$INGRESS_PORT_SUFFIX/"
-        fi
-        CONSOLE_PORT=10086
-        ;;
-    *)
-        ENABLE_CONSOLE_KUBERNETES=true
-        if [ x"$DEFAULT_NAMESPACE" != x"" ]; then
-            CONSOLE_URL="$INGRESS_PROTOCOL://console-$SESSION_NAMESPACE.$INGRESS_DOMAIN$INGRESS_PORT_SUFFIX/#/overview?namespace=$DEFAULT_NAMESPACE"
-        else
-            CONSOLE_URL="$INGRESS_PROTOCOL://console-$SESSION_NAMESPACE.$INGRESS_DOMAIN$INGRESS_PORT_SUFFIX/"
-        fi
-        CONSOLE_PORT=10083
-        ;;
-    esac
-fi
-
-if [ x"$ENABLE_EDITOR" == x"true" ]; then
-    EDITOR_URL="$INGRESS_PROTOCOL://editor-$SESSION_NAMESPACE.$INGRESS_DOMAIN$INGRESS_PORT_SUFFIX/"
-    EDITOR_PORT=10085
-fi
-
-if [ x"$ENABLE_WORKSHOP" == x"true" ]; then
-    WORKSHOP_PORT=10082
-fi
-
-WORKSHOP_URL=${WORKSHOP_URL:-$(workshop-definition -r '(.spec.session.applications.workshop.url // "")')}
-
-export ENABLE_CONSOLE_KUBERNETES
-export ENABLE_CONSOLE_OCTANT
-
-export CONSOLE_URL
-export EDITOR_URL
-
-export CONSOLE_PORT
-export EDITOR_PORT
-export HTTPD_PORT
-export WORKSHOP_PORT
-
-export WORKSHOP_URL
-
 # Download any remote workshop content hosted on a remote server. The primary
 # way of doing this is using vendir, the configuration for which is mounted into
 # the workshop container by the operator. An older obsolete way is still
@@ -172,7 +100,7 @@ export WORKSHOP_URL
 # updates. In both cases we will not fail when we can't download the workshop
 # content. The file $HOME/.local/share/workshop/download-workshop.failed will be
 # created in the event of an error so that the dashboard can display an error.
-# Output from downloading the files is save for debugging purposes to the file
+# Output from downloading the files is saved for debugging purposes to the file
 # $HOME/.local/share/workshop/download-workshop.log.
 
 DOWNLOAD_LOGFILE=$HOME/.local/share/workshop/download-workshop.log
@@ -187,8 +115,8 @@ if [ -f /opt/eduk8s/config/downloads.yaml ]; then
     else
         # In this case workshop content was already downloaded from an init
         # container so we only need to merge the workshop content. Copy the
-        # marker file for a failure and the log file to same location as the
-        # download when down in the main container.
+        # marker file for a failure and the log file to the same location as
+        # when the download is done in the main container.
 
         if [ -f /opt/downloads/download-workshop.failed ]; then
             touch $DOWNLOAD_FAILED
@@ -210,71 +138,86 @@ else
     fi
 fi
 
-# Work out location of the workshop content. This will be in workshop user home
-# directory if mounting local directory, or is a custom workshop image but files
-# were not moved to /opt/workshop. The will be /opt/workshop when moved to this
-# location as part of custom workshop image or download-workshop was used. It
-# will be /opt/eduk8s/workshop if a custom workshop base image added its own
-# default content to be used when a workshop hasn't supplied any content.
+# Run workshop specific setup scripts and then source the corresponding profile
+# scripts as well so they are available for later setup scripts. Note that any
+# errors in the profile scripts can cause the workshop container to not start.
+# Since we cannot capture what happens in profile scripts into the log file, and
+# because the container will not actually start anyway, it is necessary to look
+# at the container log file instead. An error in setup scripts on the other
+# hand shouldn't usually cause the container to not start and the log can be
+# consulted from within the workshop session container.
 
-WORKSHOP_DIR=""
+SETUP_LOGFILE=$HOME/.local/share/workshop/setup-scripts.log
+SETUP_FAILED=$HOME/.local/share/workshop/setup-scripts.failed
 
-if [ -d $HOME/workshop ]; then
-    WORKSHOP_DIR=$HOME/workshop
-else
-    if [ -d /opt/workshop ]; then
-        WORKSHOP_DIR=/opt/workshop
-    else
-        if [ -d /opt/eduk8s/workshop ]; then
-            WORKSHOP_DIR=/opt/eduk8s/workshop
-        fi
+rm -f $SETUP_FAILED
+
+rm -f $SETUP_LOGFILE
+touch $SETUP_LOGFILE
+
+function execute_setup_script() {
+    local script=$1
+    echo "Executing: $script"
+    sh -x $script || touch $SETUP_FAILED || true
+}
+
+for script in /opt/eduk8s/etc/setup.d/*.sh; do
+    if [ -x "$script" ]; then
+        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
     fi
-fi
+done
 
-export WORKSHOP_DIR
-
-# Work out location of slides if provided. The locations might be used for same
-# reasons as given for main workshop content.
-#
-# XXX This should perhaps only look under the directory specified by
-# WORKSHOP_DIR set above. It also could perhaps be moved into the gateway as not
-# needed by workshop renderer or in terminals.
-
-SLIDES_DIR=""
-
-if [ -d $HOME/workshop/slides ]; then
-    SLIDES_DIR=$HOME/workshop/slides
-else
-    if [ -d /opt/workshop/slides ]; then
-        SLIDES_DIR=/opt/workshop/slides
-    else
-        if [ -d /opt/eduk8s/workshop/slides ]; then
-            SLIDES_DIR=/opt/eduk8s/workshop/slides
-        fi
+for script in /opt/eduk8s/etc/profile.d/*.sh /opt/eduk8s/etc/profile.d/sh.local; do
+    if [ -r "$script" ]; then
+        echo "Source: $script"
+        . "$script"
     fi
-fi
+done
 
-export SLIDES_DIR
+for script in /opt/downloads/packages/*/setup.d/*.sh; do
+    if [ -x "$script" ]; then
+        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
+    fi
+done
 
-if [ x"$SLIDES_DIR" != x"" ]; then
-    SLIDES_URL="$INGRESS_PROTOCOL://$SESSION_NAMESPACE.$INGRESS_DOMAIN$INGRESS_PORT_SUFFIX/slides/"
-fi
+for script in /opt/downloads/packages/*/profile.d/*.sh /opt/downloads/packages/*/profile.d/sh.local; do
+    if [ -r "$script" ]; then
+        echo "Source: $script"
+        . "$script"
+    fi
+done
 
-export SLIDES_URL
+for script in /opt/workshop/setup.d/*.sh; do
+    if [ -x "$script" ]; then
+        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
+    fi
+done
 
-# Set the working directory for workshop exercises. The working directory for
-# the editor and terminal will be changed to this directory so any extra files
-# and directories in the home directory are not as visible.
+for script in /opt/workshop/profile.d/*.sh /opt/workshop/profile.d/sh.local; do
+    if [ -r "$script" ]; then
+        echo "Source: $script"
+        . "$script"
+    fi
+done
 
-EXERCISES_DIR=${EXERCISES_DIR:-exercises}
+for script in $HOME/workshop/setup.d/*.sh; do
+    if [ -x "$script" ]; then
+        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
+    fi
+done
 
-if [ -d $HOME/$EXERCISES_DIR ]; then
-    TERMINAL_HOME=$HOME/$EXERCISES_DIR
-    export TERMINAL_HOME
+for script in $HOME/workshop/profile.d/*.sh $HOME/workshop/profile.d/sh.local; do
+    if [ -r "$script" ]; then
+        echo "Source: $script"
+        . "$script"
+    fi
+done
 
-    EDITOR_HOME=$HOME/$EXERCISES_DIR
-    export EDITOR_HOME
-fi
+# Run supervisord. See /opt/eduk8s/etc/supervisord.conf for the main
+# configuration. This is also symlinked to /etc/supervisord.conf so that
+# supervisorctl can find it without needing to provide a command line argument
+# to tell it. We dump out the shell environment to the logs for debugging
+# purposes when something goes wrong.
 
 ENABLE_EDITOR_PROCESS=$ENABLE_EDITOR
 ENABLE_HTTPD_PROCESS=false
@@ -312,86 +255,6 @@ fi
 
 export ENABLE_WORKSHOP_PROCESS
 
-# Run workshop specific setup scripts and then source the corresponding profile
-# scripts.
-
-SETUP_LOGFILE=$HOME/.local/share/workshop/setup-scripts.log
-SETUP_FAILED=$HOME/.local/share/workshop/setup-scripts.failed
-
-rm -f $SETUP_FAILED
-
-rm -f $SETUP_LOGFILE
-touch $SETUP_LOGFILE
-
-function execute_setup_script() {
-    local script=$1
-    echo "Executing: $script"
-    sh -x $script || touch $SETUP_FAILED || true
-}
-
-for script in /opt/eduk8s/etc/setup.d/*.sh; do
-    if [ -x "$script" ]; then
-        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
-    fi
-done
-
-for i in /opt/eduk8s/profile.d/*.sh /opt/eduk8s/profile.d/sh.local; do
-    if [ -r "$i" ]; then
-        . "$i" >/dev/null
-    fi
-done
-
-for script in /opt/eduk8s/workshop/setup.d/*.sh; do
-    if [ -x "$script" ]; then
-        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
-    fi
-done
-
-for i in /opt/eduk8s/workshop/profile.d/*.sh /opt/eduk8s/workshop/profile.d/sh.local; do
-    if [ -r "$i" ]; then
-        . "$i" >/dev/null
-    fi
-done
-
-for script in /opt/downloads/packages/*/setup.d/*.sh; do
-    if [ -x "$script" ]; then
-        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
-    fi
-done
-
-for i in /opt/downloads/packages/*/profile.d/*.sh /opt/downloads/packages/*/profile.d/sh.local; do
-    if [ -r "$i" ]; then
-        . "$i" >/dev/null
-    fi
-done
-
-for script in /opt/workshop/setup.d/*.sh; do
-    if [ -x "$script" ]; then
-        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
-    fi
-done
-
-for i in /opt/workshop/profile.d/*.sh /opt/workshop/profile.d/sh.local; do
-    if [ -r "$i" ]; then
-        . "$i" >/dev/null
-    fi
-done
-
-for script in $HOME/workshop/setup.d/*.sh; do
-    if [ -x "$script" ]; then
-        execute_setup_script $script 2>&1 | tee -a $SETUP_LOGFILE
-    fi
-done
-
-for i in $HOME/workshop/profile.d/*.sh $HOME/workshop/profile.d/sh.local; do
-    if [ -r "$i" ]; then
-        . "$i" >/dev/null
-    fi
-done
-
-# Run supervisord. See /opt/eduk8s/etc/supervisord.conf for the main
-# configuration. This is also symlinked to /etc/supervisord.conf so that
-# supervisorctl can find it without needing to provide a command line argument
-# to tell it.
+env
 
 exec supervisord --nodaemon
