Add downloading of workshop content using vendir.

diff --git a/workshop-images/base-environment/opt/eduk8s/bin/update-workshop b/workshop-images/base-environment/opt/eduk8s/bin/update-workshop
--- a/workshop-images/base-environment/opt/eduk8s/bin/update-workshop
+++ b/workshop-images/base-environment/opt/eduk8s/bin/update-workshop
@@ -1,10 +1,14 @@
 #!/bin/bash
 
-if [ ! -f /home/eduk8s/.eduk8s/workshop-files.txt ]; then
-  echo "Error: Workshop has not previously been downloaded." >&2
-  exit 1
-fi
+if [ -f /opt/eduk8s/config/downloads.yaml ]; then
+  vendir-workshop
+else
+  if [ ! -f /home/eduk8s/.eduk8s/workshop-files.txt ]; then
+    echo "Error: Workshop has not previously been downloaded." >&2
+    exit 1
+  fi
 
-download-workshop --force `cat /home/eduk8s/.eduk8s/workshop-files.txt`
+  download-workshop --force `cat /home/eduk8s/.eduk8s/workshop-files.txt`
+fi
 
 rebuild-workshop
